INSERT INTO tb_users(name,email,salary) VALUES ('Sofia','sofia@gmail.com',13400008.74);
INSERT INTO tb_users(name,email,salary) VALUES ('Joao Silva','joao@gmail.com',9276.62);
INSERT INTO tb_users(name,email,salary) VALUES ('Carlos Silva','carlos@gmail.com',7318.75);
INSERT INTO tb_users(name,email,salary) VALUES ('Adriana','adriana@gmail.com',10688.93);
INSERT INTO tb_users(name,email,salary) VALUES ('Karina','karina@gmail.com',7251.28);
INSERT INTO tb_users(name,email,salary) VALUES ('Carlos Marques','carlos@gmail.com',5485.79);
INSERT INTO tb_users(name,email,salary) VALUES ('Carlos Pereira','carlos@gmail.com',3519.41);
INSERT INTO tb_users(name,email,salary) VALUES ('Ana Maria','ana@gmail.com',2569.20);
INSERT INTO tb_users(name,email,salary) VALUES ('Beatriz','beatriz@gmail.com',3853.33);
INSERT INTO tb_users(name,email,salary) VALUES ('Joana','joana@gmail.com',4222.91);
INSERT INTO tb_users(name,email,salary) VALUES ('Tulio Augusto','tulio@gmail.com',9453.69);
INSERT INTO tb_users(name,email,salary) VALUES ('Augusto','augusto@gmail.com',4119.91);
INSERT INTO tb_users(name,email,salary) VALUES ('Marta','marta@gmail.com',4519.15);
INSERT INTO tb_users(name,email,salary) VALUES ('Silvio','silvio@gmail.com',5285.68);
INSERT INTO tb_users(name,email,salary) VALUES ('Washington','washington@gmail.com',6439.99);
INSERT INTO tb_users(name,email,salary) VALUES ('Teresa','teresa@gmail.com',8929.78);
INSERT INTO tb_users(name,email,salary) VALUES ('Luciano','luciano@gmail.com',3360.72);
INSERT INTO tb_users(name,email,salary) VALUES ('Fabiana','fabiana@gmail.com',2532.83);
INSERT INTO tb_users(name,email,salary) VALUES ('Fabio','fabio@gmail.com',5912.88);
INSERT INTO tb_users(name,email,salary) VALUES ('Gisele','gisele@gmail.com',7558.26);
INSERT INTO tb_users(name,email,salary) VALUES ('Larissa','larissa@gmail.com',2362.04);
INSERT INTO tb_users(name,email,salary) VALUES ('Natanael','natanael@gmail.com',6860.63);
INSERT INTO tb_users(name,email,salary) VALUES ('Meire','meire@gmail.com',3553.40);
INSERT INTO tb_users(name,email,salary) VALUES ('Ana Carolina','ana@gmail.com',1404.28);
INSERT INTO tb_users(name,email,salary) VALUES ('Filipe','filipe@gmail.com',3388.73);

INSERT INTO tb_products(description, price, quantity) VALUES ('Macbook', 8000.00, 4);
INSERT INTO tb_products(description, price, quantity) VALUES ('Macbook Pro', 2999.99, 10);
INSERT INTO tb_products(description, price, quantity) VALUES ('Samsung Galaxy S21', 899.00, 8);
INSERT INTO tb_products(description, price, quantity) VALUES ('Sony PlayStation 5', 499.99, 5);
INSERT INTO tb_products(description, price, quantity) VALUES ('Bose QuietComfort 35 II', 349.00, 3);
INSERT INTO tb_products(description, price, quantity) VALUES ('Canon EOS Rebel T7i', 799.99, 6);
INSERT INTO tb_products(description, price, quantity) VALUES ('Fitbit Charge 4', 129.95, 12);
INSERT INTO tb_products(description, price, quantity) VALUES ('Nintendo Switch', 299.99, 9);
INSERT INTO tb_products(description, price, quantity) VALUES ('LG OLED TV', 2499.00, 4);
INSERT INTO tb_products(description, price, quantity) VALUES ('Beats Solo Pro', 299.95, 7);
INSERT INTO tb_products(description, price, quantity) VALUES ('DJI Mavic Air 2', 799.00, 2);
INSERT INTO tb_products(description, price, quantity) VALUES ('Apple Watch', 600.00, 5);
INSERT INTO tb_products(description, price, quantity) VALUES ('Echo Dot', 120.00, 9);
INSERT INTO tb_products(description, price, quantity) VALUES ('LG Smart TV', 2300.00, 4);
INSERT INTO tb_products(description, price, quantity) VALUES ('iPhone 14 Pro Max', 3500.00, 8);
INSERT INTO tb_products(description, price, quantity) VALUES ('Razer Deatheadder', 56.00, 13);
INSERT INTO tb_products(description, price, quantity) VALUES ('Dell Inspiron', 1500.00, 7);
INSERT INTO tb_products(description, price, quantity) VALUES ('Apple AirPods Pro', 249.00, 7);
INSERT INTO tb_products(description, price, quantity) VALUES ('Samsung QLED TV', 1799.00, 3);
INSERT INTO tb_products(description, price, quantity) VALUES ('GoPro Hero 9 Black', 449.99, 5);
INSERT INTO tb_products(description, price, quantity) VALUES ('Microsoft Surface Pro 7', 1299.00, 4);
INSERT INTO tb_products(description, price, quantity) VALUES ('Sonos One', 199.00, 8);
INSERT INTO tb_products(description, price, quantity) VALUES ('Nikon D850', 3299.99, 2);
INSERT INTO tb_products(description, price, quantity) VALUES ('Bose SoundLink Revolve+', 299.00, 6);
INSERT INTO tb_products(description, price, quantity) VALUES ('Sony WH-1000XM4', 349.99, 3);
INSERT INTO tb_products(description, price, quantity) VALUES ('Google Nest Hub', 89.99, 10);